### PR TITLE
fix: refresh text editor content on html or formControl changes

### PR DESCRIPTION
**Pull request by volodymyro-in6k**

### CODE REVIEW

**Comment by Sibiraj-S** [comment]
I have tried this. also, I tried this even simpler. but the problem is the cursor position when you start to type. will go to the beginning. That's why taking time.

**Comment by volodymyro-in6k** [comment]
@Sibiraj-S hello, I see, I have been looking for it for two days..
here is an example of it (https://jsfiddle.net/nrx9yvw9/5/) may be we can get is as the start point

**Comment by Sibiraj-S** [comment]
@volodymyro-in6k . I fixed it. look at the release v3.0.0.

**Comment by volodymyro-in6k** [comment]
@Sibiraj-S nice,
But Have you solved the cursor issue? When it’s starts on the beginning after content is refreshed

**Comment by Sibiraj-S** [comment]
Yes. By implementing an extra check.

1. When the content updates from external(via subscription or anything else), it won't be relevant to the existing content. 
At that time. With `ngOnChanges`. I update the content inside the editor. But only when the information isn't similar.

https://github.com/Sibiraj-S/ngx-editor/blob/3b6601807af96a14b761634a2f8719baeb6f852c/src/app/ngx-editor/ngx-editor.component.ts#L113

This line makes sure that the content inside the editor isn't refreshed all the time, which makes the cursor goes to the beginning by storing the last model value. 

2. The rest is same as usual.

**Comment by Sibiraj-S** [comment]
I have also made few changes. I updated angular/cli too. CLI has lots of problems after 1.5 release.

**Comment by Sibiraj-S** [comment]
@volodymyro-in6k what do you think.

**Pull request closed without merging**
